In [2]:
import os

import keras as keras
import numpy as np
import pandas as pd

In [3]:
dfClassCAD = pd.read_csv('/Users/niklasklein/HackathonData/CAD/ClassCAD_train.csv')
CAD = dfClassCAD.to_numpy()

In [4]:
dfClassCAD.shape

(572, 40)

In [5]:
dfClassCAD.head(
)

sample_ID  Bacteria;Abditibacteriota;Abditibacteria  \
0    H26709                                         0   
1    H26781                                         0   
2    H26800                                         0   
3    H26721                                         0   
4    H27098                                         0   

   Bacteria;Acidobacteriota;Aminicenantia  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

   Bacteria;Acidobacteriota;Blastocatellia  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   Bacteria;Actinobacteriota;Acidimicrobiia  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Actinobacteriota;Actinobacteria  \
0                                         1   
1                                        17   
2                                         2   
3                                         5   
4                                         0   

   Bacteria;Actinobacteriota;Coriobacteriia  \
0                                        11   
1                                       342   
2                                        33   
3                                         3   
4                                       108   

   Bacteria;Actinobacteriota;Thermoleophilia  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   

   Bacteria;Bacteroidota;Bacteroidia  \
0                               5381   
1                               2364   
2                               4583   
3                               5578   
4                              11306   

   Bacteria;Bdellovibrionota;Bdellovibrionia  ...  \
0                                          0  ...   
1                                          0  ...   
2                                          0  ...   
3                                          0  ...   
4                                          0  ...   

   Bacteria;Nitrospirota;Nitrospiria  \
0                                  0   
1                                  0   
2                                  0   
3                                  0   
4                                  0   

   Bacteria;Patescibacteria;Saccharimonadia  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Proteobacteria;Alphaproteobacteria  \
0                                            1   
1                                            0   
2                                            0   
3                                            0   
4                                           38   

   Bacteria;Proteobacteria;Gammaproteobacteria  \
0                                          367   
1                                         1016   
2                                          120   
3                                         1721   
4                                          686   

   Bacteria;Spirochaetota;Brachyspirae  Bacteria;Spirochaetota;Spirochaetia  \
0                                    0                                    0   
1                                    0                                    0   
2                                    0            

In [6]:
dfClassCKD = pd.read_csv('/Users/niklasklein/HackathonData/CKD/ClassCKD_train.csv')
CKD = dfClassCKD.to_numpy()

In [7]:
dfClassCKD.shape

(559, 40)

In [8]:
dfClassIBD = pd.read_csv('/Users/niklasklein/HackathonData/IBD/ClassIBD_train.csv')
IBD = dfClassIBD.to_numpy()

In [9]:
dfClassIBD.shape

(614, 42)

In [10]:
dfClassT2D = pd.read_csv('/Users/niklasklein/HackathonData/T2D/ClassT2D_train.csv')
T2D = dfClassT2D.to_numpy()

In [11]:
dfClassT2D.shape

(1048, 48)

In [12]:
dfClassT2D.head()

sample_ID  Bacteria;Abditibacteriota;Abditibacteria  \
0    H34099                                         0   
1    H26094                                         0   
2    H26935                                         0   
3    H25822                                         0   
4    H27104                                         0   

   Bacteria;Acidobacteriota;Aminicenantia  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

   Bacteria;Acidobacteriota;Blastocatellia  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   Bacteria;Acidobacteriota;Subgroup 19  \
0                                     0   
1                                     0   
2                                     0   
3                                     0   
4                                     0   

   Bacteria;Acidobacteriota;Vicinamibacteria  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   

   Bacteria;Actinobacteriota;Acidimicrobiia  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Actinobacteriota;Actinobacteria  \
0                                       148   
1                                         0   
2                                         2   
3                                         4   
4                                         3   

   Bacteria;Actinobacteriota;Coriobacteriia  \
0                                       818   
1                                         9   
2                                        35   
3                                        22   
4                                        11   

   Bacteria;Actinobacteriota;Thermoleophilia  ...  \
0                                          0  ...   
1                                          0  ...   
2                                          0  ...   
3                                          0  ...   
4                                          0  ...   

   Bacteria;Patescibacteria;Parcubacteria  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

   Bacteria;Patescibacteria;Saccharimonadia  \
0                                         2   
1                                         0   
2                                         4   
3                                         0   
4                                         0   

   Bacteria;Proteobacteria;Alphaproteobacteria  \
0                                            0   
1                                            0   
2                                            0   
3                                            2   
4                                            0   

   Bacteria;Proteobacteria;Gammaproteobacteria  \
0                                         4973   
1                                         6592   
2                                         1678   
3                                         1622   
4                                          361   

   Bacteria;Spirochaetota;Brachyspirae  Bacteria;Spirochaetota;Spirochaetia  \
0                                    0                                    0   
1                                    0                                    0   
2 

In [13]:
all_names = []
for name in dfClassCAD.columns:
    all_names.append(name)
for name in  dfClassCKD.columns:
    if name not in all_names:
        all_names.append(name)
    else:
        continue
for name in  dfClassIBD.columns:
    if name not in all_names:
        all_names.append(name)
    else:
        continue
for name in  dfClassT2D.columns:
    if name not in all_names:
        all_names.append(name)
    else:
        continue


In [14]:
len(all_names) # wir haben 49 verschiedene Klassen

49

In [15]:
for name in all_names:
    if name not in dfClassCAD.columns:
        arr = [0] * dfClassCAD.shape[0] #create array of 0 for new column
        dfClassCAD[name] = arr
for name in all_names:
    if name not in dfClassCKD.columns:
        arr = [0] * dfClassCKD.shape[0] #create array of 0 for new column
        dfClassCKD[name] = arr
for name in all_names:
    if name not in dfClassIBD.columns:
        arr = [0] * dfClassIBD.shape[0] #create array of 0 for new column
        dfClassIBD[name] = arr
for name in all_names:
    if name not in dfClassT2D.columns:
        arr = [0] * dfClassT2D.shape[0] #create array of 0 for new column
        dfClassT2D[name] = arr

In [16]:
print(dfClassT2D.shape)
print(dfClassIBD.shape)
print(dfClassCAD.shape)
print(dfClassCKD.shape)

# Spalten sind nicht in der gleichen Reihenfolge für jedes DF

(1048, 49)
(614, 49)
(572, 49)
(559, 49)


In [17]:
dfClassT2D['label'] = dfClassT2D["label"].replace([1], 1)
dfClassCAD['label'] = dfClassCAD["label"].replace([1], 3)
dfClassCKD['label'] = dfClassCKD["label"].replace([1], 4)
dfClassIBD["label"] = dfClassIBD["label"].replace([1], 2)


In [18]:
dfClassT2D.head()

sample_ID  Bacteria;Abditibacteriota;Abditibacteria  \
0    H34099                                         0   
1    H26094                                         0   
2    H26935                                         0   
3    H25822                                         0   
4    H27104                                         0   

   Bacteria;Acidobacteriota;Aminicenantia  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

   Bacteria;Acidobacteriota;Blastocatellia  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   Bacteria;Acidobacteriota;Subgroup 19  \
0                                     0   
1                                     0   
2                                     0   
3                                     0   
4                                     0   

   Bacteria;Acidobacteriota;Vicinamibacteria  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   

   Bacteria;Actinobacteriota;Acidimicrobiia  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Actinobacteriota;Actinobacteria  \
0                                       148   
1                                         0   
2                                         2   
3                                         4   
4                                         3   

   Bacteria;Actinobacteriota;Coriobacteriia  \
0                                       818   
1                                         9   
2                                        35   
3                                        22   
4                                        11   

   Bacteria;Actinobacteriota;Thermoleophilia  ...  \
0                                          0  ...   
1                                          0  ...   
2                                          0  ...   
3                                          0  ...   
4                                          0  ...   

   Bacteria;Patescibacteria;Saccharimonadia  \
0                                         2   
1                                         0   
2                                         4   
3                                         0   
4                                         0   

   Bacteria;Proteobacteria;Alphaproteobacteria  \
0                                            0   
1                                            0   
2                                            0   
3                                            2   
4                                            0   

   Bacteria;Proteobacteria;Gammaproteobacteria  \
0                                         4973   
1                                         6592   
2                                         1678   
3                                         1622   
4                                          361   

   Bacteria;Spirochaetota;Brachyspirae  Bacteria;Spirochaetota;Spirochaetia  \
0                                    0                                    0   
1                                    0                                    0   
2                                    0                                    0   
3                                    0                                    0   
4                                    0                                    0   

   Bacteria;Synergistota;Synergisti

In [19]:
print(dfClassT2D.dtypes)

sample_ID                                      object
Bacteria;Abditibacteriota;Abditibacteria        int64
Bacteria;Acidobacteriota;Aminicenantia          int64
Bacteria;Acidobacteriota;Blastocatellia         int64
Bacteria;Acidobacteriota;Subgroup 19            int64
Bacteria;Acidobacteriota;Vicinamibacteria       int64
Bacteria;Actinobacteriota;Acidimicrobiia        int64
Bacteria;Actinobacteriota;Actinobacteria        int64
Bacteria;Actinobacteriota;Coriobacteriia        int64
Bacteria;Actinobacteriota;Thermoleophilia       int64
Bacteria;Bacteroidota;Bacteroidia               int64
Bacteria;Bdellovibrionota;Bdellovibrionia       int64
Bacteria;Bdellovibrionota;Oligoflexia           int64
Bacteria;Campilobacterota;Campylobacteria       int64
Bacteria;Chloroflexi;Anaerolineae               int64
Bacteria;Chloroflexi;Chloroflexia               int64
Bacteria;Cyanobacteria;Cyanobacteriia           int64
Bacteria;Cyanobacteria;Vampirivibrionia         int64
Bacteria;Dependentiae;Babeli

In [20]:

frames = [dfClassCAD, dfClassCKD, dfClassIBD,dfClassT2D]

result = pd.concat(frames, sort=True)

In [21]:
result.shape

(2793, 49)

In [22]:
result.head()

Bacteria;Abditibacteriota;Abditibacteria  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Acidobacteriota;Aminicenantia  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

   Bacteria;Acidobacteriota;Blastocatellia  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   Bacteria;Acidobacteriota;Subgroup 19  Bacteria;Acidobacteriota;Subgroup 5  \
0                                     0                                    0   
1                                     0                                    0   
2                                     0                                    0   
3                                     0                                    0   
4                                     0                                    0   

   Bacteria;Acidobacteriota;Vicinamibacteria  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   

   Bacteria;Actinobacteriota;Acidimicrobiia  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Actinobacteriota;Actinobacteria  \
0                                         1   
1                                        17   
2                                         2   
3                                         5   
4                                         0   

   Bacteria;Actinobacteriota;Coriobacteriia  \
0                                        11   
1                                       342   
2                                        33   
3                                         3   
4                                       108   

   Bacteria;Actinobacteriota;Thermoleophilia  ...  \
0                                          0  ...   
1                                          0  ...   
2                                          0  ...   
3                                          0  ...   
4                                          0  ...   

   Bacteria;Patescibacteria;Saccharimonadia  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Proteobacteria;Alphaproteobacteria  \
0                                            1   
1                                            0   
2                                            0   
3                                            0   
4                                           38   

   Bacteria;Proteobacteria;Gammaproteobacteria  \
0                                          367   
1                                         1016   
2                                          120   
3                                         1721   
4                                          686   

   Bacteria;Spirochaetota;Brachyspirae  Bacteria;Spirochaetota;Spirochaetia  \
0                                    0                                    0   
1                                    0                                    0   
2                                    0                                    0   
3                                

In [23]:
#remove last column = sample_id
df_original = result
df = df_original.copy()
df = df.drop(["sample_ID"], axis=1)
df["label"].replace([0], "0")
df["label"] = pd.to_numeric(df["label"])

In [24]:
df.head()

Bacteria;Abditibacteriota;Abditibacteria  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Acidobacteriota;Aminicenantia  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

   Bacteria;Acidobacteriota;Blastocatellia  \
0                                        0   
1                                        0   
2                                        0   
3                                        0   
4                                        0   

   Bacteria;Acidobacteriota;Subgroup 19  Bacteria;Acidobacteriota;Subgroup 5  \
0                                     0                                    0   
1                                     0                                    0   
2                                     0                                    0   
3                                     0                                    0   
4                                     0                                    0   

   Bacteria;Acidobacteriota;Vicinamibacteria  \
0                                          0   
1                                          0   
2                                          0   
3                                          0   
4                                          0   

   Bacteria;Actinobacteriota;Acidimicrobiia  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Actinobacteriota;Actinobacteria  \
0                                         1   
1                                        17   
2                                         2   
3                                         5   
4                                         0   

   Bacteria;Actinobacteriota;Coriobacteriia  \
0                                        11   
1                                       342   
2                                        33   
3                                         3   
4                                       108   

   Bacteria;Actinobacteriota;Thermoleophilia  ...  \
0                                          0  ...   
1                                          0  ...   
2                                          0  ...   
3                                          0  ...   
4                                          0  ...   

   Bacteria;Patescibacteria;Parcubacteria  \
0                                       0   
1                                       0   
2                                       0   
3                                       0   
4                                       0   

   Bacteria;Patescibacteria;Saccharimonadia  \
0                                         0   
1                                         0   
2                                         0   
3                                         0   
4                                         0   

   Bacteria;Proteobacteria;Alphaproteobacteria  \
0                                            1   
1                                            0   
2                                            0   
3                                            0   
4                                           38   

   Bacteria;Proteobacteria;Gammaproteobacteria  \
0                                          367   
1                                         1016   
2                                          120   
3                                         1721   
4                                          686   

   Bacteria;Spirochaetota;Brachyspirae  Bacteria;Spirochaetota;Spirochaetia  \

In [25]:
df.shape

(2793, 48)

In [27]:
import tensorflow as tf
from tensorflow.keras import layers

In [28]:
tf.__version__

'2.10.0'

In [29]:
train, val, test = np.split(df.sample(frac=1), [int(0.8*len(df)), int(0.9*len(df))])


In [30]:
print(len(train), 'training examples')
print(len(val), 'validation examples')
print(len(test), 'test examples')

2234 training examples
279 validation examples
280 test examples


In [31]:
train.shape

(2234, 48)

In [32]:
print(train.dtypes)
# Everything needs to be int64 to turn it into tensor

Bacteria;Abditibacteriota;Abditibacteria       int64
Bacteria;Acidobacteriota;Aminicenantia         int64
Bacteria;Acidobacteriota;Blastocatellia        int64
Bacteria;Acidobacteriota;Subgroup 19           int64
Bacteria;Acidobacteriota;Subgroup 5            int64
Bacteria;Acidobacteriota;Vicinamibacteria      int64
Bacteria;Actinobacteriota;Acidimicrobiia       int64
Bacteria;Actinobacteriota;Actinobacteria       int64
Bacteria;Actinobacteriota;Coriobacteriia       int64
Bacteria;Actinobacteriota;Thermoleophilia      int64
Bacteria;Bacteroidota;Bacteroidia              int64
Bacteria;Bdellovibrionota;Bdellovibrionia      int64
Bacteria;Bdellovibrionota;Oligoflexia          int64
Bacteria;Campilobacterota;Campylobacteria      int64
Bacteria;Chloroflexi;Anaerolineae              int64
Bacteria;Chloroflexi;Chloroflexia              int64
Bacteria;Cyanobacteria;Cyanobacteriia          int64
Bacteria;Cyanobacteria;Vampirivibrionia        int64
Bacteria;Dependentiae;Babeliae                

In [33]:
def dataframe_to_dataset(dataframe):
    dataframe = dataframe.copy()
    labels = dataframe.pop("label")
    ds = tf.data.Dataset.from_tensor_slices((dict(dataframe), labels))
    ds = ds.shuffle(buffer_size=len(dataframe))
    return ds




In [34]:
train_ds = dataframe_to_dataset(train)
val_ds = dataframe_to_dataset(val)
test_ds = dataframe_to_dataset(test)

In [35]:
for x, y in train_ds.take(1):
    print("Input:", x)
    print("Target:", y)

Input: {'Bacteria;Abditibacteriota;Abditibacteria': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'Bacteria;Acidobacteriota;Aminicenantia': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'Bacteria;Acidobacteriota;Blastocatellia': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'Bacteria;Acidobacteriota;Subgroup 19': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'Bacteria;Acidobacteriota;Subgroup 5': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'Bacteria;Acidobacteriota;Vicinamibacteria': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'Bacteria;Actinobacteriota;Acidimicrobiia': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'Bacteria;Actinobacteriota;Actinobacteria': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'Bacteria;Actinobacteriota;Coriobacteriia': <tf.Tensor: shape=(), dtype=int64, numpy=134>, 'Bacteria;Actinobacteriota;Thermoleophilia': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'Bacteria;Bacteroidota;Bacteroidia': <tf.Tensor: shape=(), dtype=int64, numpy=4412>, 'Bacteria;Bdellovibrionot

In [36]:
#batching
train_ds = train_ds.batch(32)
val_ds = val_ds.batch(32)
test_ds = test_ds.batch(32)

In [37]:
# create Keras.inputs()
def to_input(name):
    return keras.Input(shape=(1,), name = str(name), dtype= "int64")


In [38]:
all_inputs = []
for name in train.columns:
    all_inputs.append(to_input(name))

all_inputs = all_inputs[ : -1] #except label

In [39]:
print(all_inputs)

[<KerasTensor: shape=(None, 1) dtype=int64 (created by layer 'Bacteria;Abditibacteriota;Abditibacteria')>, <KerasTensor: shape=(None, 1) dtype=int64 (created by layer 'Bacteria;Acidobacteriota;Aminicenantia')>, <KerasTensor: shape=(None, 1) dtype=int64 (created by layer 'Bacteria;Acidobacteriota;Blastocatellia')>, <KerasTensor: shape=(None, 1) dtype=int64 (created by layer 'Bacteria;Acidobacteriota;Subgroup 19')>, <KerasTensor: shape=(None, 1) dtype=int64 (created by layer 'Bacteria;Acidobacteriota;Subgroup 5')>, <KerasTensor: shape=(None, 1) dtype=int64 (created by layer 'Bacteria;Acidobacteriota;Vicinamibacteria')>, <KerasTensor: shape=(None, 1) dtype=int64 (created by layer 'Bacteria;Actinobacteriota;Acidimicrobiia')>, <KerasTensor: shape=(None, 1) dtype=int64 (created by layer 'Bacteria;Actinobacteriota;Actinobacteria')>, <KerasTensor: shape=(None, 1) dtype=int64 (created by layer 'Bacteria;Actinobacteriota;Coriobacteriia')>, <KerasTensor: shape=(None, 1) dtype=int64 (created by la

In [40]:
print(all_inputs[0].name)

Bacteria;Abditibacteriota;Abditibacteria


In [41]:
def encode_numerical_feature(feature, name, dataset):
    # Create a Normalization layer for our feature
    normalizer = layers.Normalization()

    # Prepare a Dataset that only yields our feature
    feature_ds = dataset.map(lambda x, y: x[name])
    feature_ds = feature_ds.map(lambda x: tf.expand_dims(x, -1))

    # Learn the statistics of the data
    normalizer.adapt(feature_ds)

    # Normalize the input feature
    encoded_feature = normalizer(feature)
    return encoded_feature


In [42]:
print(all_inputs[0].name)
print(len(all_inputs))

Bacteria;Abditibacteriota;Abditibacteria
47


In [43]:
first_layer = encode_numerical_feature(all_inputs[0],all_inputs[0].name,train_ds)
print(first_layer)

KerasTensor(type_spec=TensorSpec(shape=(None, 1), dtype=tf.float32, name=None), name='normalization/truediv:0', description="created by layer 'normalization'")


2023-01-05 10:56:29.662350: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


In [44]:
encoded_list = []
length = 47
for i in range(46):
   encoded_list.append(encode_numerical_feature(all_inputs[i],all_inputs[i].name,train_ds))

In [45]:
print(encoded_list)

[<KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_1')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_2')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_3')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_4')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_5')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_6')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_7')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_8')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_9')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_10')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_11')>, <KerasTensor: shape=(None, 1) dtype=float32 (created by layer 'normalization_12')>, 

In [46]:
all_features = layers.concatenate(encoded_list)

In [47]:
x = layers.Dense(32, activation="relu") (all_features)
x = layers.Dropout(0.5)(x)
output = layers.Dense(1, activation = "sigmoid") (x)

In [48]:
model = keras.Model(all_inputs, output)
model.compile("adam", "binary_crossentropy", metrics=["accuracy"])

In [49]:
model.fit(train_ds, epochs=50, validation_data=val_ds)

Epoch 1/50
70/70 [==============================] - 1s 5ms/step - loss: 0.7616 - accuracy: 0.6347 - val_loss: 63656.1016 - val_accuracy: 0.7276
Epoch 2/50
70/70 [==============================] - 0s 2ms/step - loss: 0.7283 - accuracy: 0.6862 - val_loss: 59195.9766 - val_accuracy: 0.7384
Epoch 3/50
70/70 [==============================] - 0s 2ms/step - loss: 0.7152 - accuracy: 0.7090 - val_loss: 57423.6914 - val_accuracy: 0.7455
Epoch 4/50
70/70 [==============================] - 0s 2ms/step - loss: 0.6631 - accuracy: 0.7198 - val_loss: 55210.0430 - val_accuracy: 0.7563
Epoch 5/50
70/70 [==============================] - 0s 2ms/step - loss: 0.6544 - accuracy: 0.7363 - val_loss: 54628.7891 - val_accuracy: 0.7491
Epoch 6/50
70/70 [==============================] - 0s 2ms/step - loss: 0.6244 - accuracy: 0.7305 - val_loss: 53696.1641 - val_accuracy: 0.7527
Epoch 7/50
70/70 [==============================] - 0s 2ms/step - loss: 0.6230 - accuracy: 0.7377 - val_loss: 53253.4492 - val_accuracy:

In [50]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 Bacteria;Abditibacteriota;Abdi  [(None, 1)]         0           []                               
 tibacteria (InputLayer)                                                                          
                                                                                                  
 Bacteria;Acidobacteriota;Amini  [(None, 1)]         0           []                               
 cenantia (InputLayer)                                                                            
                                                                                                  
 Bacteria;Acidobacteriota;Blast  [(None, 1)]         0           []                               
 ocatellia (InputLayer)                                                                       